zorro-project/zorro

- starknet/contracts/seed_profiles.cairo
- starknet/contracts/zorro.cairo
- starknet/test/test.py
- web/scripts/exportSeedProfiles.ts
This compiles, but the call to `_test_add_seed_profiles` in the deploy contract fails. Started trying to debug that but StarkNet seems to have temporarily gone down (?) during testing since unrelated parts of the deploy script started failing. Will circle back to this later.
> DRAFT: Refactor to read seeds from another file

- redwood/.env.defaults
- redwood/api/db/migrations/20220103153259_cache_cid_lookups/migration.sql
- redwood/api/db/schema.prisma
- redwood/api/src/lib/serializers.test.ts
- redwood/api/src/lib/starknet.ts
- redwood/api/src/tasks/syncStarknetState.ts
- redwood/package.json
- redwood/scripts/seed.ts
- redwood/scripts/syncStarknetState.ts
Don't look up the contents of profile CIDs on Infura every time if they're already stashed in our database.
Also, did this as a new migration since we now have a production deployment. Used `yarn rw prisma migrate dev` for that; quite painless!
> Cache profile CIDs

- redwood/api/db/migrations/20220103141407_create_notifications/migration.sql
- redwood/api/db/schema.prisma
- redwood/api/src/services/notifications/notifications.test.ts
- redwood/api/src/services/notifications/notifications.ts
- redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts
- redwood/api/src/tasks/syncStarknetState.test.ts
- redwood/api/src/tasks/syncStarknetState.ts
This PR sends a text message to the notaries whenever a new challenge is created.
To ensure notifications are delivered only once, I implemented a "Notification" table and `maybeNotify(key, notificationFunction)` function. 
The function first checks whether a Notification has already been created with the matching key. (I use Postgres's `jsonb` column type, so it shouldn't be sensitive to eg. changing the order of fields.) Assuming no notification has already been created, it calls the `notificationFunction` which is responsible for actually sending the notification.
It works like this:
```js
maybeNotify({ type: 'PROFILE_CREATED', id: 1 }, sendMyNotificationFn)
```
Since we now have a production deployment I also created a new migration for this by running `yarn rw prisma migrate dev`, …
> Notify notaries when a new challenge is submitted

- .github/workflows/redwood-ci.yml
Run `yarn rw tsc` on all pull requests. I'll use follow-up PRs to enable the jest tests and lint, this is more about getting the CI infrastructure set up correctly.
> Run typechecking on all pull requests

- redwood/api/src/graphql/cachedProfiles.sdl.ts
- redwood/api/src/lib/serializers.test.ts
- redwood/api/src/lib/serializers.ts
- redwood/api/src/services/cachedProfiles/cachedProfiles.ts
- redwood/api/src/tasks/syncStarknetState.ts
- redwood/web/src/layouts/UserContext.tsx
Use the `getAddress` helper from ethers.js, which returns the checksummed version https://github.com/zorro-project/zorro/pull/21#discussion_r778488304.
Also renames `cachedProfileByEthAddress` to `cachedProfileByEthereumAddress` https://github.com/zorro-project/zorro/pull/22#discussion_r778581063.
> Correctly serialize Ethereum addresses

- redwood/web/package.json
- redwood/web/src/components/ConnectButton/AccountModal.tsx
- redwood/web/src/layouts/UserContext.tsx
- redwood/yarn.lock
I have some logic in the onboarding flow where we automatically redirect you to the "connect account" page if you're on a later page but don't have an account connected currently. Unfortunately, when you first load a page ethers.js *always* tells you that there's no account connected, and then after a few milliseconds comes back and says "just kidding, an account is connected after all." Unfortunately, by that time I've already redirected the user.
This "fixes" that behavior by storing the currently-connected Ethereum address to localStorage, and ignoring `ethers.js` if it tells us that no account is connected in the first second after pageload.
This is an ugly hack, but can't think of an obviously better way to solve the problem.
> Persist the user's ethereum account across pageloads

- redwood/.eslintrc.js
- redwood/api/src/lib/starknet.ts
- redwood/api/src/services/notifications/notifications.ts
- redwood/web/src/components/ConnectButton/AccountModal.tsx
- redwood/web/src/components/Identicon.tsx
- redwood/web/src/lib/ipfs.ts
- redwood/web/src/lib/pusher.ts
Disables the "react-hooks/exhaustive-deps" rule as previously discussed, and fixes all other lint warnings.
> Fix all lint warnings

- redwood/web/src/index.html
- redwood/web/src/pages/SplashPage/SplashPage.tsx
1. Use og: tags for cross-platform sharing
2. Change the page title from "Zorro | Zorro" to "Zorro: web3 citizenship"
> Landing page tweaks

- redwood/web/src/components/links.tsx
This lets us use RLinks to create buttons that act as links to other pages within the Redwood app.
> Forward the ref for RLinks

- redwood/api/jest.config.js
- redwood/api/src/lib/serializers.test.ts
- redwood/api/src/lib/serializers.ts
- redwood/api/src/tasks/syncStarknetState.test.ts
- redwood/api/src/tasks/syncStarknetState.ts
We should probably assume that a 0 in a timestamp felt means `null`, not January 1 1970.
> Treat a StarkNet 0 as a null for timestamps

- redwood/.eslintrc.js
- redwood/api/db/migrations/20220114112028_create_users/migration.sql
- redwood/api/db/schema.prisma
- redwood/api/src/graphql/unsubmittedProfiles.sdl.ts
- redwood/api/src/graphql/users.sdl.ts
- redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts
- redwood/api/src/services/users/users.ts
- redwood/scripts/seed.ts
- redwood/web/src/layouts/UserContext.tsx
- redwood/web/src/lib/pusher.ts
- redwood/web/src/pages/SignUp/EmailPage/EmailPage.tsx
- redwood/web/src/pages/SignUp/ReviewPage/ReviewPage.tsx
- redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.tsx
Updates the schema to move emails off of the `unsubmittedProfile` model so we can use them in the future.
Also adds a new screen to the sign-up flow to capture email addresses.
> Persistent emails

- redwood/web/src/Routes.tsx
- redwood/web/src/components/requireEthAddress.tsx
- redwood/web/src/config/theme.ts
- redwood/web/src/layouts/AppLayout/AppLayout.tsx
- redwood/web/src/layouts/AppLayout/ToastManager.tsx
- redwood/web/src/layouts/NavLayout/NavBar.tsx
- redwood/web/src/layouts/NavLayout/NavLayout.tsx
- redwood/web/src/lib/util.ts
- redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.tsx
- redwood/web/src/pages/SignUp/AllowCameraPage/AllowCameraPage.stories.tsx
- redwood/web/src/pages/SignUp/AllowCameraPage/AllowCameraPage.tsx
- redwood/web/src/pages/SignUp/ConnectWalletPage/ConnectWalletPage.tsx
- redwood/web/src/pages/SignUp/EmailPage/EmailPage.stories.tsx
- redwood/web/src/pages/SignUp/EmailPage/EmailPage.tsx
- redwood/web/src/pages/SignUp/IntroPage/IntroPage.tsx
- redwood/web/src/pages/SignUp/PhotoPage/PhotoPage.stories.tsx
- redwood/web/src/pages/SignUp/PhotoPage/PhotoPage.tsx
- redwood/web/src/pages/SignUp/SignUpLayout.tsx
- redwood/web/src/pages/SignUp/SubmitPage/SubmitPage.stories.tsx
- redwood/web/src/pages/SignUp/SubmitPage/SubmitPage.tsx
- redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.stories.tsx
- redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.tsx
- redwood/web/src/pages/SignUp/Title.tsx
- redwood/web/src/pages/SignUp/UserMediaBox.tsx
- redwood/web/src/pages/SignUp/VideoPage/VideoPage.stories.tsx
- redwood/web/src/pages/SignUp/VideoPage/VideoPage.tsx
- redwood/web/src/state/signUpSlice.ts
This lets us remove the navbar from the sign up layout without losing the toast functionality.
EDIT: also makes many tweaks to the sign-in flow as tracked at https://www.notion.so/28e2b02ecf064dfe9162db3360ec6643?v=daacc4a6fb8e4ae2bd532ff4a16dcce4&p=6565e3e29f2e425d9117b71a186b9834
> Refactor AppLayout to extract navbar

- chain/contracts/starknet/seed_profiles.cairo
- redwood/api/package.json
- redwood/api/src/lib/starknet.ts
- redwood/web/package.json
- redwood/web/src/App.tsx
- redwood/web/src/components/ConnectButton/ConnectButton.tsx
- redwood/web/src/layouts/NavLayout/NavBar.tsx
- redwood/web/src/layouts/UserContext.tsx
- redwood/web/src/lib/StoryMocks.tsx
- redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.tsx
- redwood/web/src/pages/CreateConnectionPage/CreateConnectionPage.tsx
- redwood/web/src/pages/Register/EmailPage/EmailPage.tsx
- redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx
- redwood/yarn.lock
Replace https://www.npmjs.com/package/@usedapp/core with https://www.npmjs.com/package/wagmi. `wagmi` is very new (only ~a month old) but seems better factored, has good test coverage and just seems more sane in general. This should fix the annoying warnings we get in the console about trying to access deprecated methods.
> replace useDApp with wagmi

- redwood/.env.defaults
- redwood/api/src/lib/protocolNotifications.ts
- redwood/api/src/services/cachedProfiles/cachedProfiles.ts
- redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts
- redwood/api/src/tasks/syncStarknetState.ts
This circular dependency was causing `syncStarknetState` to be undefined within `unsubmittedProfiles`, causing an error when a profile was submitted.
> Fix circular dependency on `syncStarknetState <-> unsubmittedProfiles`.

- .gitignore
- redwood/api/package.json
- redwood/api/src/functions/getVerifiedExternalAddresses/getVerifiedExternalAddresses.ts
- redwood/api/src/functions/graphql.ts
- redwood/api/src/lib/backgroundJobs.ts
- redwood/api/src/services/cachedProfiles/cachedProfiles.ts
- redwood/api/src/services/cachedProfiles/helpers.ts
- redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts
- redwood/api/src/tasks/syncStarknetState.ts
- redwood/package.json
- redwood/scripts/syncStarknetState.ts
- redwood/yarn.lock
This was easier than I had feared! https://github.com/graphile/worker seems like a really solid library that works well out of the box. Has support for cron jobs, exponential backoff and job deduping via an arbitrary key out of the box. Even plays nicely with Redwood's way of reloading the server, automatically killing old jobs and then restarting them when the server comes back up!
Added a scheduled job to run the `syncStarknetState` once an hour. This is really just a placeholder to make sure scheduled jobs work—we'll want to be more sophisticated in the way we refresh our cached-profile cache eventually.
The one "downside" is that it doesn't come with a web UI. We'll probably need to build some tools to monitor task status eventually.
> Add graphile-worker for lightweight background jobs

- redwood/web/src/components/ConnectButton/ConnectButton.tsx
e.g. uniswap does this, and absent it there ends up being a "Connect Wallet" button which looks clickable but that does nothing when you click it.
> connect button busy while connecting

- chain/artifacts/contracts/starknet/zorro.cairo/zorro_abi.json
- redwood/api/db/migrations/20220127133251_user_sessions/migration.sql
- redwood/api/db/schema.prisma
- redwood/api/src/directives/requireAuth/requireAuth.test.ts
- redwood/api/src/directives/requireAuth/requireAuth.ts
- redwood/api/src/functions/graphql.ts
- redwood/api/src/graphql/unsubmittedProfiles.sdl.ts
- redwood/api/src/graphql/users.sdl.ts
- redwood/api/src/lib/auth.test.ts
- redwood/api/src/lib/auth.ts
- redwood/api/src/services/users/users.test.ts
- redwood/api/src/services/users/users.ts
- redwood/web/package.json
- redwood/web/src/App.tsx
- redwood/web/src/Routes.tsx
- redwood/web/src/config/theme.ts
- redwood/web/src/layouts/UserContext.tsx
- redwood/web/src/lib/authClient.ts
- redwood/web/src/lib/guards.ts
- redwood/web/src/lib/util.ts
- redwood/web/src/pages/AuthenticatePage/AuthenticatePage.tsx
- redwood/web/src/pages/Register/AllowCameraPage/AllowCameraPage.tsx
- redwood/web/src/pages/Register/EmailPage/EmailPage.tsx
- redwood/web/src/pages/Register/IntroPage/IntroPage.tsx
- redwood/web/src/pages/Register/PhotoPage/PhotoPage.tsx
- redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx
- redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx
- redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
- redwood/web/src/pages/UnsubmittedProfilesPage/UnsubmittedProfilesPage.tsx
- redwood/yarn.lock
Allow users to authenticate themselves by signing a server-provided one-time-use string.
This is useful for allowing notaries to submit an "intention to notarize" client-side that we can then trust to perform the actual notarization server-side.
Our original plan was to perform all notarization and profile submission client-side, but unfortunately StarkNet is being slow and unreliable and so we need to be able to track and retry failed submissions, which this allows us to do more easily.
> Use sign-in with Ethereum and Redwood auth

- redwood/web/src/lib/api.ts
- redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.tsx
- redwood/web/src/pages/Register/SelfSubmitPage/SelfSubmitPage.tsx
- redwood/web/src/pages/TestTransactionPage/TestTransactionPage.tsx
Let's keep a bit of a closer eye on the interface between the server and client code by centralizing all the code the web client imports from the API side in one place.
> Organize API imports

- redwood/api/db/migrations/20220128204428_connect_registration_attempts_to_cached_profiles/migration.sql
- redwood/api/db/schema.prisma
- redwood/api/src/chain/serializers.test.ts
- redwood/api/src/functions/getVerifiedExternalAddresses/getVerifiedExternalAddresses.ts
- redwood/api/src/graphql/registrationAttempts.sdl.ts
- redwood/api/src/services/connections/connections.ts
- redwood/api/src/services/registrationAttempts/registrationAttempts.ts
- redwood/api/src/tasks/syncStarknetState.test.ts
- redwood/api/src/tasks/syncStarknetState.ts
- redwood/web/src/pages/ProfilesPage/ProfileCard.tsx
- redwood/web/src/pages/ProfilesPage/ProfilesPage.stories.tsx
- redwood/web/src/pages/ProfilesPage/ProfilesPage.tsx
Show approved but unsubmitted profiles on the /profiles page.
Still need to feed these through to the `getVerifiedExternalAddresses` endpoint somehow, and possibly make individual profile pages for them?
> Show approved profiles on the "All Profiles" page optimistically

- redwood/api/src/directives/validateAddress/validateAddress.test.ts
- redwood/api/src/directives/validateAddress/validateAddress.ts
- redwood/api/src/graphql/cachedProfiles.sdl.ts
- redwood/api/src/graphql/registrationAttempts.sdl.ts
- redwood/api/src/graphql/users.sdl.ts
- redwood/api/src/services/registrationAttempts/registrationAttempts.ts
- redwood/scripts/seed.ts
Allow any address format that passes the `getAddress` check from ethers.js, and transforms it into a canonical form.
> Validate addresses on their way both in and out of the system

- redwood/api/src/services/registrationAttempts/helpers.ts
- redwood/api/src/services/registrationAttempts/registrationAttempts.ts
- redwood/api/src/tasks/syncStarknetState.ts
There's an eslint rule that should catch this `eslint-plugin-import/no-cycle`. For some reason it's not working, maybe because of the way Redwood roots work? Should probably get that figured out so this doesn't keep happening.
> Fix error in `submitRegistrationAttempt` caused by circular dependency

- redwood/web/src/pages/Register/MinimalVideoPlayer.tsx
- redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx
- redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx
- redwood/web/src/pages/Register/UserMediaBox.tsx
- redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
If the user's webcam or video doesn't match our 16/9 aspect ratio, inset their video so the full FOV is visible within the box and just show gray bars for the extra padding.
This ensures you can always see the full video you will be uploading to avoid any embarassing or compromising items near the video edges.
Example with vertical video:
Before:
After:
> Ensure video is never cropped

- redwood/web/src/pages/Register/RegisterScreen.tsx
Mostly to silence the warnings for using the `any` type.
> Add explicit types to RegisterScreen

- redwood/web/src/pages/Register/MinimalVideoPlayer.tsx
- redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
Automatically play your video back to you once you're done recording, and disable the "Use this video" button until playback finishes.
I thought through different button states we could use to either trigger playback or indicate that you have to play the video before you can continue, and in the end this seemed like the cleanest solution. I'm not 100% sure it's the right solution, but am very interested in seeing how it goes in user testing!
> Automatically play the video after you finish recording

- redwood/api/src/lib/config.ts
- redwood/api/src/lib/twilio.ts
- redwood/api/src/services/registrationAttempts/registrationAttempts.ts
- redwood/web/src/lib/guards.ts
I'm able to send messages both locally using the staging env vars and from the staging server itself using the Redwood console. However, messages still aren't being sent to notaries as part of the app flow. Debug traces to figure out what's going wrong.
> Log statements to debug Twilio not sending messages

- redwood/api/src/lib/twilio.ts
- redwood/api/src/services/registrationAttempts/registrationAttempts.ts
Looks like this was a result of forgetting an `await` call when persisting the registration attempt. As a result, the `pendingCount` was 0 and we skipped sending notifications.
> Fix twilio not sending messages

- render.yaml
If we're doing contract changes or data migrations, we may want more control over the deploy pipeline.
> Don't autodeploy staging

- redwood/api/src/lib/backgroundJobs.ts
- redwood/api/src/tasks/submitRegistrationAttempt.ts
Ensures we don't get in a loop running a bunch of `syncStarknetState` jobs one after another, and also makes sure we don't try to run multiple `submitRegistrationAttempt`s in parallel to decrease our chances of getting 503 errors.
> Avoid running unnecessary jobs in series or parallel

- redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
This switches our video recordings to a set of codecs that it seems both Chrome and Firefox are happy with, and removes a weird workaround that the previous codec needed to be accepted by Infura but the new one can get away without.
> Use a video codec that Firefox understands

- redwood/web/src/layouts/UserContext.tsx
Don't ask for a signature unless you've clicked "Connect Wallet". This means that eg. if you switch accounts from within Metamask, instead of being asked to sign immediately, you're shown the page in an unconnected state. The next time you click "Connect Wallet", assuming you're already connected, the signature prompt will pop up.
> Only ask for a signature if you explicitly clicked the "Connect Wallet" button
