starknet/package.json, starknet/test/build_cache.py, web/web/src/Routes.tsx, web/web/src/lib/intendedConnectionStorage.ts, web/web/src/pages/SignUpPage/SignUpPage.tsx
- improve documentation of testing commands
- ingest intended connection target
=> save snapshot space id / addr

redwood/api/src/lib/starknet.ts, redwood/web/src/components/ConnectButton/ConnectButton.tsx, redwood/web/src/components/PlaceholderCell/PlaceholderCell.tsx, redwood/web/src/components/links.tsx, redwood/web/src/lib/ipfs.ts, redwood/web/src/pages/CreateProfilePage/CreateProfilePage.tsx, redwood/web/src/pages/CreateProfilePage/PendingApprovalView.tsx, redwood/web/src/pages/CreateProfilePage/PhotoField.tsx, redwood/web/src/pages/CreateProfilePage/VideoField.tsx, redwood/web/src/pages/ProfilePage/ChallengeLink.tsx, redwood/web/src/pages/ProfilePage/ProfilePage.stories.tsx, redwood/web/src/pages/ProfilesPage/ProfilesPage.tsx, redwood/web/src/pages/TestTransactionPage/TestTransactionPage.tsx, redwood/web/src/pages/UnsubmittedProfilesPage/UnsubmittedProfile.tsx, redwood/web/tsconfig.json
Also fixes the "connect wallet" button which broke when I renamed address -> ethereumAddress a while ago.
=> Fix all type errors

redwood/api/src/services/cachedProfiles/cachedProfiles.ts, redwood/api/src/services/contractCache/contractCache.ts, redwood/api/src/tasks/syncStarknetState.ts, redwood/scripts/syncStarknetState.ts
Changes based on feedback from https://github.com/zorro-project/zorro/pull/15
=> PR feedback

redwood/api/db/migrations/20220104123847_rename_address/migration.sql, redwood/api/db/schema.prisma, redwood/api/src/graphql/unsubmittedProfiles.sdl.ts, redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts, redwood/api/src/tasks/syncStarknetState.test.ts, redwood/scripts/seed.ts, redwood/web/src/Routes.tsx, redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/layouts/UserContext.tsx, redwood/web/src/lib/getNotaryKey.ts, redwood/web/src/pages/CreateProfilePage/CreateProfilePage.tsx, redwood/web/src/pages/CreateProfilePage/PendingApprovalView.tsx, redwood/web/src/pages/SignUp/IntroPage/IntroPage.tsx, redwood/web/src/pages/SignUp/SignUpLayout.tsx, redwood/web/src/pages/UnsubmittedProfilesPage/UnsubmittedProfilesPage.tsx
Renames the "address" column to "ethAddress" on the UnsubmittedProfile page to be consistent with the naming in the contract.
Also created a top-level "SignUpLayout" that will hold context related to the signup state.
=> Rename "address" -> "ethAddress"

.github/workflows/redwood-ci.yml, redwood/api/src/lib/starknet.ts, redwood/api/src/lib/twilio.ts, starknet/chain-deployments/test/adjudicator.json, starknet/chain-deployments/test/admin.json, starknet/chain-deployments/test/challenger.json, starknet/chain-deployments/test/erc20.json, starknet/chain-deployments/test/minter.json, starknet/chain-deployments/test/notary.json, starknet/chain-deployments/test/zorro.json
This PR adds support for running the Redwood test suite on every pull request.
=> Run Redwood tests on all pull requests

redwood/web/src/Routes.tsx, redwood/web/src/index.html, redwood/web/src/pages/SplashPage/SplashPage.tsx
(twitter's scraper bot doesn't run js)
=> render meta tags on server

redwood/api/package.json, redwood/api/src/directives/requireAuth/requireAuth.ts, redwood/api/src/functions/getVerifiedExternalAddresses/getVerifiedExternalAddresses.ts, redwood/api/src/lib/auth.ts, redwood/api/src/lib/starknet.ts, redwood/api/src/services/cachedProfiles/cachedProfiles.ts, redwood/api/src/services/connections/connections.ts, redwood/api/src/services/unsubmittedProfiles/unsubmittedProfiles.ts, redwood/api/tsconfig.json, redwood/tsconfig-base.json, redwood/web/package.json, redwood/web/src/components/Identicon.tsx, redwood/web/src/components/requireEthAddress.tsx, redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/pages/CreateConnectionPage/CreateConnectionPage.tsx, redwood/web/src/pages/ProfilesPage/ProfilesPage.tsx, redwood/web/src/pages/SignUp/IntroPage/IntroPage.tsx, redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.tsx, redwood/web/src/pages/TestTransactionPage/TestTransactionPage.tsx, redwood/web/tsconfig.json, redwood/yarn.lock
I've found that a tighter TS configuration can catch a lot of bugs before users see them. This PR turns on the [noImplicitAny](https://www.typescriptlang.org/tsconfig#noImplicitAny) config option and fixes all the affected types.
=> Enable the `noImplicitAny` Typescript configuration

redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.tsx
Looks a bit nicer and gives us more control.
=> Use Chakra's toast instead of Redwood's

redwood/web/package.json, redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/layouts/AppLayout/NavBar.tsx, redwood/yarn.lock
Need the page to be the full viewport height to push some buttons to the bottom as part of the signup flow.
This also has an unrelated fix to make sure we always close the mobile menu on page navigation and fix mobile menu spacing.
=> Make sure the page is always at least the full viewport height

redwood/web/package.json, redwood/web/src/Routes.tsx, redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/pages/SignUp/AllowCameraPage/AllowCameraPage.tsx, redwood/web/src/pages/SignUp/ConnectWalletPage/ConnectWalletPage.tsx, redwood/web/src/pages/SignUp/EditPage/EditPage.tsx, redwood/web/src/pages/SignUp/IntroPage/IntroPage.tsx, redwood/web/src/pages/SignUp/SignUpLayout.tsx, redwood/yarn.lock
Also fixed some bugs introduced by recent AppLayout changes.
=> Allow camera page

redwood/web/src/Routes.tsx, redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.stories.tsx, redwood/web/src/pages/SignUp/EmailPage/EmailPage.tsx, redwood/web/src/pages/SignUp/ReviewPage/ReviewPage.tsx, redwood/web/src/pages/SignUp/SignUpLayout.tsx, redwood/web/src/pages/SignUp/SubmitPage/SubmitPage.stories.tsx, redwood/web/src/pages/SignUp/SubmitPage/SubmitPage.tsx, redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.tsx
We'll insert another page between these two to collect email. Was going to add the email page as part of this PR, but need to do some refactoring of where we store the email first.
=> Split review and submit pages

redwood/.eslintrc.js, redwood/web/config/storybook.config.js, redwood/web/config/storybook.preview.js, redwood/web/package.json, redwood/web/src/layouts/UserContext.tsx, redwood/web/src/lib/StoryMocks.tsx, redwood/web/src/pages/SignUp/AllowCameraPage/AllowCameraPage.stories.tsx, redwood/web/src/pages/SignUp/ConnectWalletPage/ConnectWalletPage.stories.tsx, redwood/web/src/pages/SignUp/IntroPage/IntroPage.stories.tsx, redwood/web/src/pages/SignUp/RecordPage/RecordPage.stories.tsx, redwood/web/src/pages/SignUp/RecordPage/RecordPage.tsx, redwood/web/src/pages/SignUp/ReviewPage/ReviewPage.stories.tsx, redwood/web/src/pages/SignUp/SubmitPage/SubmitPage.stories.tsx, redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.stories.tsx, redwood/web/src/pages/SignUp/SubmittedPage/SubmittedPage.tsx, redwood/yarn.lock
I realized I was starting to slow down because of how long it takes to navigate between different states in the sign-up flow. Adding them all to Storybook with appropriate mocks to speed up the feedback loop.
Also added some Storybook infra to make mocking easier.
=> Add Storybook previews for all the important sign-up states

redwood/run_tests.sh, redwood/web/src/pages/Register/EmailPage/EmailPage.tsx, redwood/web/src/pages/Register/IntroPage/IntroPage.tsx, redwood/web/src/pages/Register/RegisterLayout.tsx, redwood/web/src/pages/Register/RegisterLogo.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
A number of fixes from https://hackmd.io/onam45GWTQWs6wFf1oMKAg?view , most prominently vertically centering the content and adding a light drop-shadow.
=> Visual tweaks, including vertically centering content

CONTRIBUTING.md, redwood/README.md, redwood/package.json, redwood/run_checks.sh
Might want to add a reminder to run this as a precommit hook or something.
EDIT: also made some partial updates to the READMEs.
=> Add `yarn run-checks`

redwood/web/src/lib/util.ts, redwood/web/src/pages/Register/EmailPage/EmailPage.tsx, redwood/web/src/pages/Register/PhotoPage/PhotoPage.tsx, redwood/web/src/pages/Register/RegisterLayout.tsx, redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
=> More tweaks to the signup flow

redwood/api/src/lib/ipfs.ts, redwood/api/src/services/registrationAttempts/registrationAttempts.ts, redwood/api/src/tasks/submitRegistrationAttempt.ts, redwood/web/src/lib/ipfs.ts, redwood/web/src/lib/util.ts, redwood/web/src/pages/ChallengeProfilePage/ChallengeProfilePage.tsx, redwood/web/src/pages/TestTransactionPage/TestTransactionPage.tsx
This PR makes the `submitRegistrationAttempt` job functional. We can now submit profiles from our server!
=> Actually import profiles server-side

redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.stories.tsx, redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx
We optimistically assume that if a notary has approved your profile, it'll go through at some point.
=> SubmittedPage ignores cached profiles and goes off of notary status

redwood/web/src/Routes.tsx, redwood/web/src/components/SquareBox.tsx, redwood/web/src/lib/pusher.ts, redwood/web/src/pages/PendingProfilePage/PendingProfilePage.stories.tsx, redwood/web/src/pages/PendingProfilePage/PendingProfilePage.tsx, redwood/web/src/pages/ProfilePage/ProfilePage.tsx, redwood/web/src/pages/ProfilesPage/ProfileCard.tsx, redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx
https://github.com/zorro-project/zorro/pull/100 ended up in a bad state due to a rebase and I didn't catch it in time. This PR includes the actual implementation of the pending profile page!
=> Implementation for https://github.com/zorro-project/zorro/pull/100

chain/contracts/starknet/profile.cairo, chain/contracts/starknet/zorro.cairo
At first I thought we could get away without this because we weren't relying on the default dict initial value, but realized it's still necessary because `squash_dict` (which is called by `finalize_default_dict`) also does some assertion work.
=> Finalize default dict — necessary to guard against malicious sequencer

redwood/api/src/graphql/contractCache.sdl.ts, redwood/api/src/services/cachedProfiles/cachedProfiles.ts, redwood/api/src/services/cachedProfiles/helpers.ts, redwood/api/src/services/contractCache/contractCache.ts
Follow-up for the same rename on the Cairo side to keep the nomenclature consistent.
=> Rename all TimeWindow fields to Period

redwood/web/src/pages/Register/MinimalVideoPlayer.tsx, redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx, redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
Probably what users expect to be able to do.
=> Click video again to pause it

redwood/web/src/lib/guards.ts, redwood/web/src/pages/Register/EmailPage/EmailPage.tsx, redwood/web/src/pages/Register/PhotoPage/PhotoPage.tsx, redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
Every step (especially the submit page!) should probably check that you don't already have an approved or registered profile.
=> More register guards

infra/posthog/README.md, infra/posthog/values.yaml, redwood/web/package.json, redwood/web/src/components/ConnectButton/ConnectButton.tsx, redwood/web/src/layouts/AppLayout/AppLayout.tsx, redwood/web/src/lib/posthog.ts, redwood/web/src/pages/Register/AllowCameraPage/AllowCameraPage.tsx, redwood/web/src/pages/Register/EmailPage/EmailPage.tsx, redwood/web/src/pages/Register/IntroPage/IntroPage.tsx, redwood/web/src/pages/Register/PhotoPage/PhotoPage.tsx, redwood/web/src/pages/Register/SubmitPage/SubmitPage.tsx, redwood/web/src/pages/Register/SubmittedPage/SubmittedPage.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx, redwood/yarn.lock
Explicitly track some events in a self-hosted Posthog installation to see where users are getting lost or confused.
=> Posthog tracking

redwood/web/package.json, redwood/web/src/components/ConnectButton/AccountModal.tsx, redwood/web/src/components/ConnectButton/ConnectButton.tsx, redwood/web/src/pages/Register/IntroPage/IntroPage.tsx, redwood/yarn.lock
Let users know that we currently only support MetaMask on desktop. Gives them a link to ask for wider wallet support.
=> Educate mobile/no-metamask users

redwood/web/src/components/ConnectButton/ConnectButton.tsx, redwood/web/src/global.d.ts, redwood/web/types/globals.d.ts
Make sure you really don't have Metamask.
=> Fix check for missing wallet

redwood/web/src/components/ConnectButton/ConnectButton.tsx
Accidentally removed this in a prior commit.
=> Restore loading state on ConnectButton

redwood/web/src/pages/Register/SubmitPage/SubmitPage.stories.tsx, redwood/web/src/pages/Register/VideoPage/VideoPage.tsx
There are other more impactful changes we can make, but this seems like an easy low-hanging fruit.
=> Make the oath text bigger

render.yaml
Going to push a new deployment to Render to see whether I can successfully connect with WalletConnect.
=> Staging frontend experiments
